# Project: Practica3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = P3main.o polinomio.o PolinomiosOp.o
LINKOBJ  = P3main.o polinomio.o PolinomiosOp.o
LIBS     = -L"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib" -L"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Practica3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

P3main.o: P3main.cpp
	$(CPP) -c P3main.cpp -o P3main.o $(CXXFLAGS)

polinomio.o: polinomio.cpp
	$(CPP) -c polinomio.cpp -o polinomio.o $(CXXFLAGS)

PolinomiosOp.o: PolinomiosOp.cpp
	$(CPP) -c PolinomiosOp.cpp -o PolinomiosOp.o $(CXXFLAGS)
