# Project: Pila
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o PilaPs.o PilaD.o
LINKOBJ  = main.o PilaPs.o PilaD.o
LIBS     = -L"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib" -L"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/PROGRAMAS/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Pila.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

PilaPs.o: PilaPs.cpp
	$(CPP) -c PilaPs.cpp -o PilaPs.o $(CXXFLAGS)

PilaD.o: PilaD.cpp
	$(CPP) -c PilaD.cpp -o PilaD.o $(CXXFLAGS)
